<a href="https://colab.research.google.com/github/KokXiang/CSIS3053-2026A-Midterm-Test-Q3/blob/main/CSIS3053_2026A_Midterm_Test_Q3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Load the Excel file into a pandas DataFrame
file_path = '/content/Q3_Student_Dataset_DT_KNN_Noise.xlsx'
df = pd.read_excel(file_path)

# Display the first 5 rows of the DataFrame
display(df.head())

  Student_ID  Attendance_Percent  Assignment_Avg  Quiz_Avg Final_Result
0        S01                  83              55        43         Fail
1        S02                  95              52        92         Fail
2        S03                  70              55        50         Pass
3        S04                  49              86        55         Fail
4        S05                  68              84        63         Pass

In [ ]:
# Display basic information about the DataFrame, including data types and non-null values
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          30 non-null     object
 1   Attendance_Percent  30 non-null     int64
 2   Assignment_Avg      30 non-null     int64
 3   Quiz_Avg            30 non-null     int64
 4   Final_Result        30 non-null     object
dtypes: int64(3), object(2)
memory usage: 1.3+ KB

None

### Midterm Test Questions

**(a) Identify input features and target variable.**

**Explanation:**
*   **Input Features:** `Attendance_Percent`, `Assignment_Avg`, `Quiz_Avg`. These are the numerical attributes used to predict the outcome.
*   **Target Variable:** `Final_Result`. This is the categorical variable we aim to predict ('Pass' or 'Fail'). The `Student_ID` is an identifier and will be excluded from modeling.

**(b) Describe TWO preprocessing steps and explain their purpose.**

**Explanation:**
1.  **Categorical Feature Encoding for 'Final_Result':** The `Final_Result` column was converted from 'Pass'/'Fail' (object type) to numerical values (1/0). This is essential because most machine learning algorithms require numerical input. This transformation allows the model to process the target variable correctly.
2.  **Dropping 'Student_ID' column:** The `Student_ID` column, being a unique identifier, has no predictive power for the `Final_Result`. It was dropped to prevent the model from learning irrelevant patterns and to avoid potential overfitting, simplifying the model and improving its generalization ability.

**(c) Identify ONE pattern from the dataset.**

**Explanation:**
A clear pattern observed is the relationship between the numerical performance metrics (`Attendance_Percent`, `Assignment_Avg`, `Quiz_Avg`) and the `Final_Result`. It is highly probable that students with higher values in these academic and participation metrics are more likely to achieve a 'Pass', while those with lower values are more prone to 'Fail'. This suggests a direct correlation between student engagement/performance indicators and their final academic outcome.

**(d) Suggest ONE suitable evaluation metric and justify.**

**Explanation:**
*   **Suggested Metric: F1-Score.**
*   **Justification:** The `Final_Result` is a binary classification problem ('Pass' or 'Fail'). The F1-Score is a harmonic mean of Precision and Recall, providing a balanced measure that considers both false positives and false negatives. It is particularly useful when there might be class imbalance (e.g., more 'Pass' than 'Fail' outcomes, or vice-versa) or when the costs of misclassifying either 'Pass' or 'Fail' are significant. Given that the dataset might contain 'noise' and requires careful justification of metrics, F1-Score offers a robust evaluation of the model's ability to correctly identify both classes, which is more informative than simple accuracy alone in such scenarios.

In [ ]:
from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df_processed.drop('Final_Result', axis=1)
y = df_processed['Final_Result']

# Split the dataset into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Display the shapes of the resulting datasets
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (24, 3)
X_test shape: (6, 3)
y_train shape: (24,)
y_test shape: (6,)

In [ ]:
# Drop the 'Student_ID' column
df_processed = df.drop('Student_ID', axis=1)

# Encode 'Final_Result' column: 'Pass' to 1, 'Fail' to 0
df_processed['Final_Result'] = df_processed['Final_Result'].map({'Pass': 1, 'Fail': 0})

# Display the first few rows of the processed DataFrame
display(df_processed.head())

   Attendance_Percent  Assignment_Avg  Quiz_Avg  Final_Result
0                  83              55        43             0
1                  95              52        92             0
2                  70              55        50             1
3                  49              86        55             0
4                  68              84        63             1

In [ ]:
# Display the info of the processed DataFrame to confirm changes
display(df_processed.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Attendance_Percent  30 non-null     int64
 1   Assignment_Avg      30 non-null     int64
 2   Quiz_Avg            30 non-null     int64
 3   Final_Result        30 non-null     int64
dtypes: int64(4)
memory usage: 1.1 KB

None